//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilenioApi.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulo()
        {
            this.Imagen = new HashSet<Imagen>();
        }
    
        public System.Guid Codigo_Id { get; set; }
        public string Nombre { get; set; }
        public string Referencia { get; set; }
        public string Descripcion { get; set; }
        public string Marca { get; set; }
        public int ValorUnitario { get; set; }
        public int PrecioIn { get; set; }
        public int PrecioOut { get; set; }
        public Nullable<bool> Estado { get; set; }
        public System.Guid Subcategoria_Id { get; set; }
        public System.Guid Usuario_Id { get; set; }
        public System.DateTime Created_At { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagen> Imagen { get; set; }
        public virtual Subcategoria Subcategoria { get; set; }
    }
}
