
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MilenioApi.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class Articulo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Articulo()
    {

        this.Imagen = new HashSet<Imagen>();

    }


    public System.Guid Codigo_Id { get; set; }

    public int Codigo { get; set; }

    public string Nombre { get; set; }

    public System.Guid Subcategoria_Id { get; set; }

    public string Referencia { get; set; }

    public string Serial_Lote { get; set; }

    public string Codigo_Contable { get; set; }

    public string Descripcion { get; set; }

    public Nullable<System.Guid> Marca_Id { get; set; }

    public string Modelo { get; set; }

    public string Color { get; set; }

    public string Talla { get; set; }

    public string Udm { get; set; }

    public string Foto { get; set; }

    public Nullable<bool> Estado { get; set; }

    public System.Guid Usuario_Update { get; set; }

    public System.DateTime Created_At { get; set; }

    public System.DateTime Updated_At { get; set; }



    public virtual Marca Marca { get; set; }

    public virtual Subcategoria Subcategoria { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Imagen> Imagen { get; set; }

}

}
