
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MilenioApi.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class Cita
{

    public System.Guid Id_Cita { get; set; }

    public System.Guid Id_Paciente { get; set; }

    public System.Guid Id_Entidad { get; set; }

    public Nullable<System.Guid> Id_Especialidad { get; set; }

    public System.Guid Id_Cup { get; set; }

    public System.Guid Id_Detalle_Agenda { get; set; }

    public string Cod_Aprobacion { get; set; }

    public bool Confirmada { get; set; }

    public System.DateTime Fecha_Create { get; set; }



    public virtual Detalle_Agenda Detalle_Agenda { get; set; }

    public virtual Paciente Paciente { get; set; }

}

}
