
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MilenioApi.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class Consultorio_Especialidad
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Consultorio_Especialidad()
    {

        this.Agenda_Profesional = new HashSet<Agenda_Profesional>();

    }


    public System.Guid Id_Consultorio { get; set; }

    public System.Guid Id_Especialidad { get; set; }

    public System.Guid Id_Entidad { get; set; }

    public bool Estado { get; set; }

    public System.Guid Usuario_Create { get; set; }

    public System.DateTime Fecha_Create { get; set; }

    public System.Guid Usuario_Update { get; set; }

    public System.DateTime Fecha_Update { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Agenda_Profesional> Agenda_Profesional { get; set; }

    public virtual Consultorio Consultorio { get; set; }

    public virtual Especialidad_Entidad Especialidad_Entidad { get; set; }

}

}
