//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilenioApi.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Agenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detalle_Agenda()
        {
            this.Cita = new HashSet<Cita>();
        }
    
        public System.Guid Id_Detalle_Agenda { get; set; }
        public System.Guid Id_Horario_Agenda { get; set; }
        public System.DateTime Hora_Desde { get; set; }
        public System.DateTime Hora_Hasta { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Asignada { get; set; }
        public System.DateTime Fecha_Create { get; set; }
        public System.DateTime Fecha_Update { get; set; }
        public System.Guid Usuario_Create { get; set; }
        public System.Guid Usuario_Update { get; set; }
        public Nullable<System.Guid> Id_Suplente { get; set; }
    
        public virtual Horario_Agenda Horario_Agenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Cita { get; set; }
    }
}
