
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MilenioApi.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class Entidad
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Entidad()
    {

        this.Entidad_Usuario = new HashSet<Entidad_Usuario>();

        this.Especialidad_Cup_Entidad = new HashSet<Especialidad_Cup_Entidad>();

        this.Especialidad_Entidad = new HashSet<Especialidad_Entidad>();

        this.Licencia = new HashSet<Licencia>();

        this.Rol_Vista_Entidad = new HashSet<Rol_Vista_Entidad>();

        this.Telefono1 = new HashSet<Telefono>();

    }


    public System.Guid Id_Entidad { get; set; }

    public string Nit { get; set; }

    public string Nombre { get; set; }

    public string Organizacion { get; set; }

    public string Direccion { get; set; }

    public Nullable<int> Poblado_Id { get; set; }

    public string Email { get; set; }

    public string Telefono { get; set; }

    public string CodigoEntidad { get; set; }

    public bool Atencion_Prioritaria { get; set; }

    public bool Contribuyente { get; set; }

    public string Foto { get; set; }

    public string Hora_Desde { get; set; }

    public string Hora_Hasta { get; set; }

    public Nullable<System.Guid> Usuario_Update { get; set; }

    public Nullable<System.DateTime> Fecha_Update { get; set; }

    public Nullable<System.DateTime> Fecha_Create { get; set; }



    public virtual Poblado Poblado { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Entidad_Usuario> Entidad_Usuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Especialidad_Cup_Entidad> Especialidad_Cup_Entidad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Especialidad_Entidad> Especialidad_Entidad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Licencia> Licencia { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rol_Vista_Entidad> Rol_Vista_Entidad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Telefono> Telefono1 { get; set; }

}

}
