
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MilenioApi.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class Entidad
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Entidad()
    {

        this.Especialidad_Entidad = new HashSet<Especialidad_Entidad>();

        this.Licencia = new HashSet<Licencia>();

        this.Profesional = new HashSet<Profesional>();

        this.Telefono = new HashSet<Telefono>();

        this.Usuario = new HashSet<Usuario>();

    }


    public System.Guid Id_Entidad { get; set; }

    public int Nit { get; set; }

    public string Nombre { get; set; }

    public int CodigoEntidad { get; set; }

    public string Foto { get; set; }

    public System.DateTime FiniFiscal { get; set; }

    public System.DateTime FfinFiscal { get; set; }

    public Nullable<System.Guid> Ubicacion_Id { get; set; }

    public Nullable<System.DateTime> Usuario_Update { get; set; }

    public Nullable<System.DateTime> Fecha_Update { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Especialidad_Entidad> Especialidad_Entidad { get; set; }

    public virtual Ubicacion Ubicacion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Licencia> Licencia { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Profesional> Profesional { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Telefono> Telefono { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Usuario> Usuario { get; set; }

}

}
