
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MilenioApi.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class Entidad
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Entidad()
    {

        this.Entidad1 = new HashSet<Entidad>();

        this.Entidad_Persona_Rol = new HashSet<Entidad_Persona_Rol>();

        this.Licencia = new HashSet<Licencia>();

        this.Telefono = new HashSet<Telefono>();

    }


    public System.Guid Codigo_Id { get; set; }

    public int Nit { get; set; }

    public string Nombre { get; set; }

    public int CodigoEntidad { get; set; }

    public int CodigoDane { get; set; }

    public string Foto { get; set; }

    public System.DateTime FiniFiscal { get; set; }

    public System.DateTime FfinFiscal { get; set; }

    public Nullable<System.Guid> Entidad_Padre { get; set; }

    public Nullable<System.Guid> Ubicacion_Id { get; set; }

    public Nullable<System.DateTime> Created_At { get; set; }

    public Nullable<System.DateTime> Updated_At { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Entidad> Entidad1 { get; set; }

    public virtual Entidad Entidad2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Entidad_Persona_Rol> Entidad_Persona_Rol { get; set; }

    public virtual Ubicacion Ubicacion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Licencia> Licencia { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Telefono> Telefono { get; set; }

}

}
