
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MilenioApi.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class Entidad_Usuario
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Entidad_Usuario()
    {

        this.Rol_Usuario = new HashSet<Rol_Usuario>();

    }


    public System.Guid Id_Entidad { get; set; }

    public System.Guid Id_Usuario { get; set; }

    public bool Estado { get; set; }

    public System.Guid Usuario_Create { get; set; }

    public System.DateTime Fecha_Create { get; set; }

    public System.Guid Usuario_Update { get; set; }

    public System.DateTime Fecha_Update { get; set; }



    public virtual Entidad Entidad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rol_Usuario> Rol_Usuario { get; set; }

    public virtual Usuario Usuario { get; set; }

}

}
