
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MilenioApi.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class Especialidad
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Especialidad()
    {

        this.Especialidad_Entidad = new HashSet<Especialidad_Entidad>();

    }


    public System.Guid Id_Especialidad { get; set; }

    public string Codigo { get; set; }

    public string NombreServicio { get; set; }

    public int CodigoClase { get; set; }

    public string NombreClase { get; set; }

    public Nullable<int> CodigoSubclase { get; set; }

    public string NombreSubclase { get; set; }

    public Nullable<int> CodigoSubclase2 { get; set; }

    public string NombreSubclase2 { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Especialidad_Entidad> Especialidad_Entidad { get; set; }

}

}
