
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MilenioApi.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class Horario_Agenda
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Horario_Agenda()
    {

        this.Detalle_Agenda = new HashSet<Detalle_Agenda>();

    }


    public System.Guid Id_Horario_Agenda { get; set; }

    public System.Guid Id_Agenda_Profesional { get; set; }

    public System.Guid Id_Consultorio { get; set; }

    public System.DateTime Hora_Desde { get; set; }

    public System.DateTime Hora_Hasta { get; set; }

    public string Dia { get; set; }

    public int Duracion { get; set; }

    public System.DateTime Fecha_Create { get; set; }

    public System.DateTime Fecha_Update { get; set; }

    public System.Guid Usuario_Create { get; set; }

    public System.Guid Usuario_Update { get; set; }

    public bool Estado { get; set; }



    public virtual Agenda_Profesional Agenda_Profesional { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Detalle_Agenda> Detalle_Agenda { get; set; }

}

}
