
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MilenioApi.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class Imagen
{

    public System.Guid Codigo_Id { get; set; }

    public System.Guid Fuente_Id { get; set; }

    public string RutaImagen { get; set; }

    public System.DateTime Created_At { get; set; }

    public Nullable<System.DateTime> Updated_At { get; set; }



    public virtual Articulo Articulo { get; set; }

    public virtual Persona Persona { get; set; }

}

}
