
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MilenioApi.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class Profesional
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Profesional()
    {

        this.Especialidad_Profesional = new HashSet<Especialidad_Profesional>();

        this.Telefono = new HashSet<Telefono>();

    }


    public System.Guid Id_Profesional { get; set; }

    public System.Guid Id_Usuario { get; set; }

    public System.Guid Id_Tipo_Profesional { get; set; }

    public string Registro_Profesional { get; set; }

    public System.DateTime Created_At { get; set; }

    public System.DateTime Updated_At { get; set; }

    public Nullable<System.Guid> Usuario_Update { get; set; }

    public Nullable<System.Guid> Usuario_Create { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Especialidad_Profesional> Especialidad_Profesional { get; set; }

    public virtual Tipo_Profesional Tipo_Profesional { get; set; }

    public virtual Usuario Usuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Telefono> Telefono { get; set; }

}

}
