
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MilenioApi.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class Proveedor
{

    public System.Guid Codigo_Id { get; set; }

    public string Razon_Socal { get; set; }

    public string Nit { get; set; }

    public string Telefono { get; set; }

    public string Direccion { get; set; }

    public string Persona_Contacto { get; set; }

    public bool Estado { get; set; }

    public System.Guid Usuario_Update { get; set; }

    public System.DateTime Created_At { get; set; }

    public string Update_At { get; set; }

}

}
