
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MilenioApi.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class Rol
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Rol()
    {

        this.Rol_Usuario = new HashSet<Rol_Usuario>();

        this.Rol_Vista_Entidad = new HashSet<Rol_Vista_Entidad>();

        this.Menu = new HashSet<Menu>();

    }


    public System.Guid Id_Rol { get; set; }

    public string Nombre { get; set; }

    public Nullable<bool> Estado { get; set; }

    public string Descripcion { get; set; }

    public Nullable<System.DateTime> Created_At { get; set; }

    public Nullable<System.DateTime> Updated_At { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rol_Usuario> Rol_Usuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rol_Vista_Entidad> Rol_Vista_Entidad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Menu> Menu { get; set; }

}

}
