//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilenioApi.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamentos_Esenciales
    {
        public System.Guid Id_Medicamento { get; set; }
        public string Codigo { get; set; }
        public string Principio_Activo { get; set; }
        public string Forma { get; set; }
        public int Concentracion { get; set; }
        public string Nombre { get; set; }
        public string Presentacion { get; set; }
    }
}
