//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilenioApi.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_Vista_Entidad
    {
        public System.Guid Id_Rol { get; set; }
        public System.Guid Id_Vista { get; set; }
        public System.Guid Id_Entidad { get; set; }
        public bool Autorizado { get; set; }
    
        public virtual Entidad Entidad { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual Vistas Vistas { get; set; }
    }
}
